insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (1, 'Bebidas');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (2, 'Almacén');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (3, 'Lácteos y Embutidos');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (4, 'Frutas y Verduras');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (5, 'Carnes');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (11, 'Alcohólicas');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (12, 'Sin Alcohol');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (21, 'Especias');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (22, 'Aceites');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (23, 'Panificados');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (24, 'Legumbres');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (25, 'Aderezos');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (31, 'Quesos');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (32, 'Fiambres');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (51, 'Blancas');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (52, 'Rojas');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (111, 'Cervezas');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (112, 'Vinos');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (121, 'Gasificadas');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (122, 'No Gasificadas');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (231, 'Integral');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (232, 'Blanco');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (1211, 'Gaseosa');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (1212, 'Soda');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (1221, 'Agua');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (1222, 'Agua Saborizada');
insert into elbuensabor.rubroinsumo (idRubroInsumo, denominacion) values (1223, 'Jugo');
